BASE = ../../../..

DEPEND = KOMO Core Geo Kin Gui Optim POMTP_interfaces TaskPlanning MotionPlanning ObservationTasks

include $(BASE)/build/generic.mk

#POMTP_interfaces/policy.h>
#include <POMTP_interfaces/policy_printer.h>

#include <TaskPlanning/policy_builder.h>

#include <TaskPlanning/mcts_planner.h>
#include <MotionPlanning/komo_planner.h>

#include <ObservationTasks/observation_tasks.h>
#include <CollisionAvoidance/approx_point_to_shape.h>
#include <CollisionAvoidance/vertical_velocity.h>
#include <CollisionAvoidance/axis_alignment.h>
#include <CollisionAvoidance/over_plane.h>

#include <TaskPlanning/node_visitors.h>
